# Generated by Django 4.0.4 on 2022-06-08 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 13, 52, 2, 177141)),
        ),
    ]
