# Generated by Django 4.0.4 on 2022-06-08 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 11, 55, 44, 971837, tzinfo=utc)),
        ),
    ]
