# Generated by Django 4.0.4 on 2022-05-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_list_listassignment_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_repeat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
