# Generated by Django 4.0.4 on 2022-05-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_end_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
