# Generated by Django 4.0.4 on 2022-05-22 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0005_alter_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned',
            field=models.ManyToManyField(blank=True, related_name='assignments', through='tasks.Assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
